### ISSUE TITLE
what's the difference "camera_points" and "line_points" ?

### ISSUE THREAD

**Issue by Thunderltx** [NikolasEnt/soccernet-calibration-sportlight#10]
I read the code , I think they are the key points， but I don't understand the specific difference

**Comment by NikolasEnt** [comment]
@Thunderltx Thank you for your interest in our project. `camera_points` in [src/models/hrnet/prediction.py](https://github.com/NikolasEnt/soccernet-calibration-sportlight/blob/master/src/models/hrnet/prediction.py) are the points predicted by the keypoints model directly, while `line_points` are keypoints inferred as intersection of lines, predicted by the line model.
