### ISSUE TITLE
Request for Pretrained Model Weights for Camera Calibration in Football

### ISSUE THREAD

**Issue by VictorVatt** [NikolasEnt/soccernet-calibration-sportlight#5]
Hello Nikolay,

I am currently working on a project that involves camera calibration parameter estimation specifically for football. For this purpose, I am interested in your model and its potential application in my work.

Due to limitations in my computational resources, I am unable to train the model from scratch. Hence, I am writing to kindly request if you could make the pretrained weights of the model available. Having access to these weights would greatly facilitate easy inference and significantly aid in the progress of my project.

Understanding the concerns regarding sharing pretrained models, I assure you that the weights would be used solely for educational and research purposes within the scope of my project.

**Comment by NikolasEnt** [comment]
Hello @VictorVatt . Thank you for your interest in our project. Sorry, unfortunately, we are not sharing the pretrained weights as for now.

**Comment by VictorVatt** [comment]
Ok thanks anyway !

**Comment by rydenisbak** [comment]
Hello @NikolasEnt! Thanks for great work! Maybe now you have possibility to share weigths ?)
