### ISSUE TITLE
Restarting training from checkpoint

### ISSUE THREAD

**Issue by petem24** [NikolasEnt/soccernet-calibration-sportlight#8]
Firstly thank you for making this repo public!

I am currently training the keypoint model and i got to epoch 13. I am now restarting from the checkpoint pth file by adding the path in train_config.yaml but it starts again from epoch -1, am I starting again from the beginning or does this not matter?

Apologies if this is obvious but this is my first time training a model

**Comment by NikolasEnt** [comment]
If you set the model checkpoint path in `model.params.pretrain`, the model is loaded and you are continuing training from the weights saved in the checkpoint file. But epoch number in the logs will start from 0, also the new epoch numbering will be used for LR scheduler.
