### ISSUE TITLE
Multi plane points - Golas planes

### ISSUE THREAD

**Issue by dorbittonn** [NikolasEnt/soccernet-calibration-sportlight#9]
Hey, thank you for your work.
@NikolasEnt  @ruilongml 
I would like to understand better how you processes the Goals planes as a valid correspondences. 

under prediction.py I see:

```
sets_transforms = {
    'groundplane': lambda x: x,
    'goal_left': swap_z_y,
    'goal_right': swap_z_y
}
```

```
        for point_set in point_sets:
            world_p = []
            camera_p = []
            for i in point_sets[point_set]:
                if i in camera_points:
                    world_p.append(
                        sets_transforms[point_set](self.pitch[
                            INTERSECTON_TO_PITCH_POINTS[i]]))
                    camera_p.append(camera_points[i])
            if len(camera_p) > 0:
                world_points_sampled.append(world_p)
                camera_points_sampled.append(camera_p)
```
                
If I understand correctly, you "flatten" the post's world points on the pitch, but how that makes sense to be a valid thing to do for calibration purposes using cv2.calibrateCamera?

thank you!

**Comment by NikolasEnt** [comment]
Hi @dorbittonn , thank you for your interest in our project and sorry for the delayed reply. The post's points are not flattened, but used as part of another surface so in total we have 3 surfaces: the pitch and two surfaces in which the goals are. You can find some details in our [paper](https://arxiv.org/abs/2410.07401) on the method, section 4.3. Please let me know if you have other questions.
